---
kind: pipeline
type: kubernetes
name: default

environment:
  GOCACHE: /cache/pkg/cache
  GOMODCACHE: /cache/pkg/mod

steps:
  - name: test
    image: golang:1.20.4
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    commands:
      - go mod vendor
      - go test -v
      - go build

  - name: docker
    image: harbor.ntppool.org/ntppool/drone-kaniko:main
    pull: always
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    settings:
      repo: ntppool/screensnap
      registry: harbor.ntppool.org
      auto_tag: true
      tags: SHA7,${DRONE_SOURCE_BRANCH}
      cache: true
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password

volumes:
  - name: go
    temp: {}
  - name: gopkg
    claim:
      name: go-pkg

---
kind: signature
hmac: d17657f7951fb128963bad847e85dec59f4e5e8b3f6a30328c402edd46de6a67

...
